#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!
sudo apt-get update
sudo apt-get -y install nginx
# Listen port 80
sudo ufw allow 'Nginx HTTP'
sudo chmod 777 /var/www/html/
sudo echo "Holberton School" > /var/www/html
sudo service nginx start
