#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!
sudo apt-get -y update
sudo apt-get -y install nginx
# Adjust the Firewall port 80
sudo ufw allow 'Nginx HTTP'
# Index file & Start Nginx
echo "Holberton School" > /var/www/html/index.html
# Redirection
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# Modifies 404 html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/err_404.html
# Configures 404 error page
sudo sed -i '/listen 80 default_server/a error_page 404 /err_404.html;' /etc/nginx/sites-available/default
# Start the server
sudo service nginx restart
