#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get update
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get install haproxy=2.0.\*