#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get update
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get install haproxy=2.0.\*
echo "fronend web_frontend
        bind*:80
        default_backend web_backend
backend web_backend
        balance roundrobin
        server web-01 34.74.126.117 check
        server web-02 34.235.137.233 check
" | sudo tee-a /etc/haproxy/haproxy.cfg
sudo servive haproxy start
