#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
echo "fronend web_frontend
        bind*:80
        default_backend web_backend
backend web_backend
        balance roundrobin
        server web-01 34.74.126.117:80 check
        server web-02 34.235.137.233:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
